apiVersion: v1
kind: Service
metadata:
        name: nemo-service
spec:
        selector:
                app: web-server
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 4000
        type: LoadBalancer
